/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
export var styles = ['div[_ngcontent-%COMP%]:last-child {\n  display: none !important; }'];
//# sourceMappingURL=videos.css.shim.js.map