/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
"use strict";
exports.styles = ['div[_ngcontent-%COMP%]:last-child {\r\n    display: none !important;\r\n}'];
//# sourceMappingURL=videos.scss.shim.js.map