/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../app/app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../app/services/services';
import * as import9 from '@angular/router/src/router';
import * as import10 from '../../app/services/page-name.service';
import * as import11 from './app.component.css.shim';
import * as import12 from '../../app/HeaderImage/header.image';
import * as import13 from './HeaderImage/header.image.ngfactory';
import * as import14 from '@angular/core/src/linker/view_container';
import * as import15 from '../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import16 from '../node_modules/@angular/router/src/directives/router_outlet.ngfactory';
import * as import17 from '../../app/pipes/pipes';
import * as import18 from '@angular/common/src/pipes/lowercase_pipe';
import * as import19 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import20 from '@angular/core/src/linker/template_ref';
import * as import21 from '@angular/router/src/router_outlet_map';
import * as import22 from '@angular/core/src/linker/component_factory_resolver';
import * as import23 from '@angular/common/src/directives/ng_if';
import * as import24 from '@angular/router/src/directives/router_outlet';
import * as import25 from '../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import26 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import27 from '@angular/common/src/directives/ng_for';
import * as import28 from '../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import29 from '../node_modules/@angular/router/src/directives/router_link_active.ngfactory';
import * as import30 from '@angular/core/src/linker/query_list';
import * as import31 from '@angular/router/src/router_state';
import * as import32 from '@angular/common/src/location/location_strategy';
import * as import33 from '@angular/core/src/linker/element_ref';
import * as import34 from '@angular/router/src/directives/router_link';
import * as import35 from '@angular/router/src/directives/router_link_active';
export class Wrapper_AppComponent {
  /*private*/ _eventHandler:Function;
  context:import0.AppComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any) {
    this._changed = false;
    this.context = new import0.AppComponent(p0,p1,p2,p3,p4);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_AppComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_AppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.AppComponent>;
  _AppComponent_0_3:Wrapper_AppComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent_Host0,renderType_AppComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'my-app',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_AppComponent0(this.viewUtils,this,0,this._el_0);
    this._AppComponent_0_3 = new Wrapper_AppComponent(this.injectorGet(import8.DataService,this.parentIndex),this.injectorGet(import8.CacheManager,this.parentIndex),this.injectorGet(import9.Router,this.parentIndex),this.injector(0),this.injectorGet(import10.pageNameService,this.parentIndex));
    this.compView_0.create(this._AppComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._AppComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AppComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._AppComponent_0_3.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const AppComponentNgFactory:import7.ComponentFactory<import0.AppComponent> = new import7.ComponentFactory<import0.AppComponent>('my-app',View_AppComponent_Host0,import0.AppComponent);
const styles_AppComponent:any[] = [import11.styles];
var renderType_AppComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_AppComponent,{});
export class View_AppComponent0 extends import1.AppView<import0.AppComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  compView_2:import1.AppView<import12.HeaderImage>;
  _HeaderImage_2_3:import13.Wrapper_HeaderImage;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _anchor_21:any;
  /*private*/ _vc_21:import14.ViewContainer;
  _TemplateRef_21_5:any;
  _NgIf_21_6:import15.Wrapper_NgIf;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  /*private*/ _vc_25:import14.ViewContainer;
  _RouterOutlet_25_5:import16.Wrapper_RouterOutlet;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _text_54:any;
  _el_55:any;
  _text_56:any;
  _text_57:any;
  _el_58:any;
  _text_59:any;
  _text_60:any;
  _el_61:any;
  _text_62:any;
  _text_63:any;
  _text_64:any;
  _el_65:any;
  _text_66:any;
  _el_67:any;
  _text_68:any;
  _text_69:any;
  _text_70:any;
  _el_71:any;
  _text_72:any;
  _el_73:any;
  _text_74:any;
  _text_75:any;
  _el_76:any;
  _text_77:any;
  _text_78:any;
  _text_79:any;
  _text_80:any;
  _text_81:any;
  _text_82:any;
  _text_83:any;
  /*private*/ _expr_91:any;
  /*private*/ _expr_92:any;
  _pipe_translate_0:import17.TranslatePipe;
  _pipe_lowercase_1:import18.LowerCasePipe;
  /*private*/ _expr_95:any;
  _pipe_translate_0_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent0,renderType_AppComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_91 = import6.UNINITIALIZED;
    this._expr_92 = import6.UNINITIALIZED;
    this._expr_95 = import6.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container-fluid'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'header-image',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_2 = new import13.View_HeaderImage0(this.viewUtils,this,2,this._el_2);
    this._HeaderImage_2_3 = new import13.Wrapper_HeaderImage(this.parentView.injectorGet(import10.pageNameService,this.parentIndex),this.parentView.injectorGet(import8.DataService,this.parentIndex),this.parentView.injectorGet(import8.LogService,this.parentIndex),this.parentView.injectorGet(import19.DomSanitizer,this.parentIndex),this.parentView.injectorGet(import9.Router,this.parentIndex));
    this.compView_2.create(this._HeaderImage_2_3.context);
    this._text_3 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row container-fluid-margin'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n\n        ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'div',new import3.InlineArray2(2,'class','btn-group-sm'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n                ',(null as any));
    this._text_10 = this.renderer.createText(this._el_8,'\n                ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_8,'button',new import3.InlineArray4(4,'class','langLinks','type','button'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'Eng',(null as any));
    this._text_13 = this.renderer.createText(this._el_8,'\n                ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_8,'button',new import3.InlineArray4(4,'class','langLinks','type','button'),(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'עבר',(null as any));
    this._text_16 = this.renderer.createText(this._el_8,'\n\n            ',(null as any));
    this._text_17 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._text_18 = this.renderer.createText(this._el_4,'\n\n    ',(null as any));
    this._text_19 = this.renderer.createText(this._el_0,'\n\n\n\n',(null as any));
    this._text_20 = this.renderer.createText(parentRenderNode,'\n\n\n\n\n',(null as any));
    this._anchor_21 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_21 = new import14.ViewContainer(21,(null as any),this,this._anchor_21);
    this._TemplateRef_21_5 = new import20.TemplateRef_(this,21,this._anchor_21);
    this._NgIf_21_6 = new import15.Wrapper_NgIf(this._vc_21.vcRef,this._TemplateRef_21_5);
    this._text_22 = this.renderer.createText(parentRenderNode,'\n\n\n\n\n\n\n',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container-fluid'),(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'\n    ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_23,'router-outlet',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._vc_25 = new import14.ViewContainer(25,23,this,this._el_25);
    this._RouterOutlet_25_5 = new import16.Wrapper_RouterOutlet(this.parentView.injectorGet(import21.RouterOutletMap,this.parentIndex),this._vc_25.vcRef,this.parentView.injectorGet(import22.ComponentFactoryResolver,this.parentIndex),(null as any));
    this._text_26 = this.renderer.createText(this._el_23,'\n\n',(null as any));
    this._text_27 = this.renderer.createText(parentRenderNode,'\n\n\n\n',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,parentRenderNode,'footer',new import3.InlineArray2(2,'id','footer'),(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'\n    ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_28,'div',new import3.InlineArray2(2,'class','container-fluid'),(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'\n        ',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_30,'div',new import3.InlineArray2(2,'class','row footer-row text-center'),(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'\n            ',(null as any));
    this._el_34 = import3.createRenderElement(this.renderer,this._el_32,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-3'),(null as any));
    this._text_35 = this.renderer.createText(this._el_34,'\n                ',(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_34,'a',new import3.InlineArray4(4,'class','h5','href','mailto:noyaschleien@gmail.com'),(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'noyaschleien@gmail.com',(null as any));
    this._text_38 = this.renderer.createText(this._el_34,'\n            ',(null as any));
    this._text_39 = this.renderer.createText(this._el_32,'\n            ',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_32,'div',new import3.InlineArray2(2,'class','col-sm-7'),(null as any));
    this._text_41 = this.renderer.createText(this._el_32,'\n            ',(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,this._el_32,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-2'),(null as any));
    this._text_43 = this.renderer.createText(this._el_42,'\n                ',(null as any));
    this._el_44 = import3.createRenderElement(this.renderer,this._el_42,'button',new import3.InlineArray2(2,'class','btn btn-primary'),(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'',(null as any));
    this._text_46 = this.renderer.createText(this._el_42,'\n            ',(null as any));
    this._text_47 = this.renderer.createText(this._el_32,'\n            ',(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,this._el_32,'hr',new import3.InlineArray2(2,'class','dl-horizontal'),(null as any));
    this._text_49 = this.renderer.createText(this._el_32,'\n            ',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_32,'div',new import3.InlineArray2(2,'class','col-sm-12 hidden-xs'),(null as any));
    this._text_51 = this.renderer.createText(this._el_50,'\n                ',(null as any));
    this._el_52 = import3.createRenderElement(this.renderer,this._el_50,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_53 = this.renderer.createText(this._el_52,'Noya Schleien@2013',(null as any));
    this._text_54 = this.renderer.createText(this._el_50,'\n                ',(null as any));
    this._el_55 = import3.createRenderElement(this.renderer,this._el_50,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_56 = this.renderer.createText(this._el_55,'|',(null as any));
    this._text_57 = this.renderer.createText(this._el_50,'\n                ',(null as any));
    this._el_58 = import3.createRenderElement(this.renderer,this._el_50,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_59 = this.renderer.createText(this._el_58,'Developed by',(null as any));
    this._text_60 = this.renderer.createText(this._el_50,'\n                ',(null as any));
    this._el_61 = import3.createRenderElement(this.renderer,this._el_50,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_62 = this.renderer.createText(this._el_61,'Future WebSites',(null as any));
    this._text_63 = this.renderer.createText(this._el_50,'\n            ',(null as any));
    this._text_64 = this.renderer.createText(this._el_32,'\n            ',(null as any));
    this._el_65 = import3.createRenderElement(this.renderer,this._el_32,'div',new import3.InlineArray2(2,'class','col-xs-12 hidden-sm hidden-md hidden-lg'),(null as any));
    this._text_66 = this.renderer.createText(this._el_65,'\n                ',(null as any));
    this._el_67 = import3.createRenderElement(this.renderer,this._el_65,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_68 = this.renderer.createText(this._el_67,'Noya Schleien@2013',(null as any));
    this._text_69 = this.renderer.createText(this._el_65,'\n            ',(null as any));
    this._text_70 = this.renderer.createText(this._el_32,'\n            ',(null as any));
    this._el_71 = import3.createRenderElement(this.renderer,this._el_32,'div',new import3.InlineArray2(2,'class','col-xs-12 hidden-sm hidden-md hidden-lg'),(null as any));
    this._text_72 = this.renderer.createText(this._el_71,'\n                ',(null as any));
    this._el_73 = import3.createRenderElement(this.renderer,this._el_71,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_74 = this.renderer.createText(this._el_73,'Developed by',(null as any));
    this._text_75 = this.renderer.createText(this._el_71,'\n                ',(null as any));
    this._el_76 = import3.createRenderElement(this.renderer,this._el_71,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_77 = this.renderer.createText(this._el_76,'Future WebSites',(null as any));
    this._text_78 = this.renderer.createText(this._el_71,'\n            ',(null as any));
    this._text_79 = this.renderer.createText(this._el_32,'\n\n        ',(null as any));
    this._text_80 = this.renderer.createText(this._el_30,'\n    ',(null as any));
    this._text_81 = this.renderer.createText(this._el_28,'\n\n\n\n\n',(null as any));
    this._text_82 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._text_83 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_11,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_11));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_14,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_14));
    this._pipe_translate_0 = new import17.TranslatePipe(this.parentView.injectorGet(import8.TranslationService,this.parentIndex),this.parentView.injectorGet(import8.CacheManager,this.parentIndex));
    this._pipe_lowercase_1 = new import18.LowerCasePipe();
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_44,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_44));
    this._pipe_translate_0_3 = import3.pureProxy1(this._pipe_translate_0.transform.bind(this._pipe_translate_0));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._anchor_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._text_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._text_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._el_73,
      this._text_74,
      this._text_75,
      this._el_76,
      this._text_77,
      this._text_78,
      this._text_79,
      this._text_80,
      this._text_81,
      this._text_82,
      this._text_83
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.HeaderImage) && (2 === requestNodeIndex))) { return this._HeaderImage_2_3.context; }
    if (((token === import20.TemplateRef) && (21 === requestNodeIndex))) { return this._TemplateRef_21_5; }
    if (((token === import23.NgIf) && (21 === requestNodeIndex))) { return this._NgIf_21_6.context; }
    if (((token === import24.RouterOutlet) && (25 === requestNodeIndex))) { return this._RouterOutlet_25_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import6.ValueUnwrapper();
    const currVal_2_0_0:any = 'home';
    this._HeaderImage_2_3.check_pageName(currVal_2_0_0,throwOnChange,false);
    this._HeaderImage_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    const currVal_21_0_0:any = this.context.displayMenu;
    this._NgIf_21_6.check_ngIf(currVal_21_0_0,throwOnChange,false);
    this._NgIf_21_6.ngDoCheck(this,this._anchor_21,throwOnChange);
    this._RouterOutlet_25_5.ngDoCheck(this,this._el_25,throwOnChange);
    this._vc_21.detectChangesInNestedViews(throwOnChange);
    this._vc_25.detectChangesInNestedViews(throwOnChange);
    const currVal_91:any = this.context.isHebrew;
    if (import3.checkBinding(throwOnChange,this._expr_91,currVal_91)) {
      this.renderer.setElementClass(this._el_6,'text-left',currVal_91);
      this._expr_91 = currVal_91;
    }
    const currVal_92:boolean = !this.context.isHebrew;
    if (import3.checkBinding(throwOnChange,this._expr_92,currVal_92)) {
      this.renderer.setElementClass(this._el_6,'text-right',currVal_92);
      this._expr_92 = currVal_92;
    }
    valUnwrapper.reset();
    const currVal_95:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_3,this._pipe_translate_0.transform)('Order Concert')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_95,currVal_95))) {
      this.renderer.setText(this._text_45,currVal_95);
      this._expr_95 = currVal_95;
    }
    this.compView_2.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_21.destroyNestedViews();
    this._vc_25.destroyNestedViews();
    this.compView_2.destroy();
    this._RouterOutlet_25_5.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 21)) { return new View_AppComponent1(this.viewUtils,this,21,this._anchor_21,this._vc_21); }
    return (null as any);
  }
  handleEvent_11(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.changeToEnglish()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_14(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.changeToHebrew()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_44(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.goToContact()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_AppComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _anchor_27:any;
  /*private*/ _vc_27:import14.ViewContainer;
  _TemplateRef_27_5:any;
  _NgFor_27_6:import25.Wrapper_NgFor;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  /*private*/ _expr_34:any;
  _pipe_translate_0_0:any;
  /*private*/ _expr_36:any;
  _pipe_translate_0_1:any;
  /*private*/ _expr_38:any;
  _pipe_translate_0_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import14.ViewContainer) {
    super(View_AppComponent1,renderType_AppComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_34 = import6.UNINITIALIZED;
    this._expr_36 = import6.UNINITIALIZED;
    this._expr_38 = import6.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray4(4,'class','navbar navbar-default my-navbar','style',''),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n\n\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','navbar-header'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'button',new import3.InlineArray8(8,'class','navbar-toggle','data-target','.navbar-collapse','data-toggle','collapse','type','button'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'span',new import3.InlineArray2(2,'style','font-weight: 900; color: white'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_2,'h4',new import3.InlineArray2(2,'class','navMenu hidden-lg hidden-md hidden-sm mobliePath'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_10,'span',new import3.InlineArray2(2,'class','white-font'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'',(null as any));
    this._text_14 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_10,'span',new import3.InlineArray2(2,'class','white-font'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'|',(null as any));
    this._text_17 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_10,'span',new import3.InlineArray2(2,'class','pageName white-font'),(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'',(null as any));
    this._text_20 = this.renderer.createText(this._el_10,'\n\n        ',(null as any));
    this._text_21 = this.renderer.createText(this._el_2,'\n\n    ',(null as any));
    this._text_22 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','navbar-collapse collapse'),(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'\n\n        ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_23,'ul',new import3.InlineArray2(2,'class','menu-ul nav nav-pills nav-justified '),(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'\n            ',(null as any));
    this._anchor_27 = this.renderer.createTemplateAnchor(this._el_25,(null as any));
    this._vc_27 = new import14.ViewContainer(27,25,this,this._anchor_27);
    this._TemplateRef_27_5 = new import20.TemplateRef_(this,27,this._anchor_27);
    this._NgFor_27_6 = new import25.Wrapper_NgFor(this._vc_27.vcRef,this._TemplateRef_27_5,this.parentView.injectorGet(import26.IterableDiffers,this.parentIndex),this.parentView.ref);
    this._text_28 = this.renderer.createText(this._el_25,'\n        ',(null as any));
    this._text_29 = this.renderer.createText(this._el_23,'\n    ',(null as any));
    this._text_30 = this.renderer.createText(this._el_0,'\n\n',(null as any));
    this._pipe_translate_0_0 = import3.pureProxy1((<View_AppComponent0>this.parentView)._pipe_translate_0.transform.bind((<View_AppComponent0>this.parentView)._pipe_translate_0));
    this._pipe_translate_0_1 = import3.pureProxy1((<View_AppComponent0>this.parentView)._pipe_translate_0.transform.bind((<View_AppComponent0>this.parentView)._pipe_translate_0));
    this._pipe_translate_0_2 = import3.pureProxy1((<View_AppComponent0>this.parentView)._pipe_translate_0.transform.bind((<View_AppComponent0>this.parentView)._pipe_translate_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._anchor_27,
      this._text_28,
      this._text_29,
      this._text_30
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.TemplateRef) && (27 === requestNodeIndex))) { return this._TemplateRef_27_5; }
    if (((token === import27.NgFor) && (27 === requestNodeIndex))) { return this._NgFor_27_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import6.ValueUnwrapper();
    const currVal_27_0_0:any = this.parentView.context.menuItems;
    this._NgFor_27_6.check_ngForOf(currVal_27_0_0,throwOnChange,false);
    this._NgFor_27_6.ngDoCheck(this,this._anchor_27,throwOnChange);
    this._vc_27.detectChangesInNestedViews(throwOnChange);
    valUnwrapper.reset();
    const currVal_34:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_0,(<View_AppComponent0>this.parentView)._pipe_translate_0.transform)('Menu')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_34,currVal_34))) {
      this.renderer.setText(this._text_7,currVal_34);
      this._expr_34 = currVal_34;
    }
    valUnwrapper.reset();
    const currVal_36:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_1,(<View_AppComponent0>this.parentView)._pipe_translate_0.transform)('Noya Schleien')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_36,currVal_36))) {
      this.renderer.setText(this._text_13,currVal_36);
      this._expr_36 = currVal_36;
    }
    valUnwrapper.reset();
    const currVal_38:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_translate_0_2,(<View_AppComponent0>this.parentView)._pipe_translate_0.transform)(this.parentView.context.pageName)),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_38,currVal_38))) {
      this.renderer.setText(this._text_19,currVal_38);
      this._expr_38 = currVal_38;
    }
  }
  destroyInternal():void {
    this._vc_27.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 27)) { return new View_AppComponent2(this.viewUtils,this,27,this._anchor_27,this._vc_27); }
    return (null as any);
  }
}
class View_AppComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _RouterLinkWithHref_2_3:import28.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_2_4:import29.Wrapper_RouterLinkActive;
  _query_RouterLink_2_0:import30.QueryList<any>;
  _query_RouterLinkWithHref_2_1:import30.QueryList<any>;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _RouterLinkWithHref_5_3:import28.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_5_4:import29.Wrapper_RouterLinkActive;
  _query_RouterLink_5_0:import30.QueryList<any>;
  _query_RouterLinkWithHref_5_1:import30.QueryList<any>;
  _text_6:any;
  _text_7:any;
  _pipe_lowercase_1_0:any;
  _arr_17:any;
  /*private*/ _expr_18:any;
  _pipe_lowercase_1_1:any;
  _arr_20:any;
  /*private*/ _expr_21:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import14.ViewContainer) {
    super(View_AppComponent2,renderType_AppComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._arr_17 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_18 = import6.UNINITIALIZED;
    this._arr_20 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_21 = import6.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'a',new import3.InlineArray8(8,'class','menu-font  menu-anchor hidden-md hidden-lg hidden-sm','data-target','.navbar-collapse','data-toggle','collapse','routerLinkActive','active-menu-item'),(null as any));
    this._RouterLinkWithHref_2_3 = new import28.Wrapper_RouterLinkWithHref(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import31.ActivatedRoute,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import32.LocationStrategy,this.parentView.parentIndex));
    this._RouterLinkActive_2_4 = new import29.Wrapper_RouterLinkActive(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),new import33.ElementRef(this._el_2),this.renderer);
    this._query_RouterLink_2_0 = new import30.QueryList<any>();
    this._query_RouterLinkWithHref_2_1 = new import30.QueryList<any>();
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_0,'a',new import3.InlineArray4(4,'class','menu-font  menu-anchor hidden-xs','routerLinkActive','active-menu-item'),(null as any));
    this._RouterLinkWithHref_5_3 = new import28.Wrapper_RouterLinkWithHref(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import31.ActivatedRoute,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import32.LocationStrategy,this.parentView.parentIndex));
    this._RouterLinkActive_5_4 = new import29.Wrapper_RouterLinkActive(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),new import33.ElementRef(this._el_5),this.renderer);
    this._query_RouterLink_5_0 = new import30.QueryList<any>();
    this._query_RouterLinkWithHref_5_1 = new import30.QueryList<any>();
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_2));
    this._pipe_lowercase_1_0 = import3.pureProxy1((<View_AppComponent0>this.parentView.parentView)._pipe_lowercase_1.transform.bind((<View_AppComponent0>this.parentView.parentView)._pipe_lowercase_1));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_5,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_5));
    this._pipe_lowercase_1_1 = import3.pureProxy1((<View_AppComponent0>this.parentView.parentView)._pipe_lowercase_1.transform.bind((<View_AppComponent0>this.parentView.parentView)._pipe_lowercase_1));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7
    ]
    ),[
      disposable_0,
      disposable_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import34.RouterLinkWithHref) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._RouterLinkWithHref_2_3.context; }
    if (((token === import35.RouterLinkActive) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._RouterLinkActive_2_4.context; }
    if (((token === import34.RouterLinkWithHref) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._RouterLinkWithHref_5_3.context; }
    if (((token === import35.RouterLinkActive) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._RouterLinkActive_5_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import6.ValueUnwrapper();
    const currVal_2_0_0:any = '.navbar-collapse';
    this._RouterLinkWithHref_2_3.check_target(currVal_2_0_0,throwOnChange,false);
    valUnwrapper.reset();
    const currVal_2_0_1:any = this._arr_17(valUnwrapper.unwrap(import3.castByValue(this._pipe_lowercase_1_0,(<View_AppComponent0>this.parentView.parentView)._pipe_lowercase_1.transform)(this.context.$implicit.Name)));
    this._RouterLinkWithHref_2_3.check_routerLink(currVal_2_0_1,throwOnChange,valUnwrapper.hasWrappedValue);
    this._RouterLinkWithHref_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    const currVal_2_1_0:any = 'active-menu-item';
    this._RouterLinkActive_2_4.check_routerLinkActive(currVal_2_1_0,throwOnChange,false);
    this._RouterLinkActive_2_4.ngDoCheck(this,this._el_2,throwOnChange);
    valUnwrapper.reset();
    const currVal_5_0_0:any = this._arr_20(valUnwrapper.unwrap(import3.castByValue(this._pipe_lowercase_1_1,(<View_AppComponent0>this.parentView.parentView)._pipe_lowercase_1.transform)(this.context.$implicit.Name)));
    this._RouterLinkWithHref_5_3.check_routerLink(currVal_5_0_0,throwOnChange,valUnwrapper.hasWrappedValue);
    this._RouterLinkWithHref_5_3.ngDoCheck(this,this._el_5,throwOnChange);
    const currVal_5_1_0:any = 'active-menu-item';
    this._RouterLinkActive_5_4.check_routerLinkActive(currVal_5_1_0,throwOnChange,false);
    this._RouterLinkActive_5_4.ngDoCheck(this,this._el_5,throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_2_0.dirty) {
        this._query_RouterLink_2_0.reset(([] as any[]));
        this._RouterLinkActive_2_4.context.links = this._query_RouterLink_2_0;
        this._query_RouterLink_2_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_2_1.dirty) {
        this._query_RouterLinkWithHref_2_1.reset([this._RouterLinkWithHref_2_3.context]);
        this._RouterLinkActive_2_4.context.linksWithHrefs = this._query_RouterLinkWithHref_2_1;
        this._query_RouterLinkWithHref_2_1.notifyOnChanges();
      }
      if (this._query_RouterLink_5_0.dirty) {
        this._query_RouterLink_5_0.reset(([] as any[]));
        this._RouterLinkActive_5_4.context.links = this._query_RouterLink_5_0;
        this._query_RouterLink_5_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_5_1.dirty) {
        this._query_RouterLinkWithHref_5_1.reset([this._RouterLinkWithHref_5_3.context]);
        this._RouterLinkActive_5_4.context.linksWithHrefs = this._query_RouterLinkWithHref_5_1;
        this._query_RouterLinkWithHref_5_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_2_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_5_4.context.ngAfterContentInit(); }
    }
    this._RouterLinkWithHref_2_3.checkHost(this,this,this._el_2,throwOnChange);
    const currVal_18:any = import3.inlineInterpolate(1,'',this.context.$implicit.Text,'');
    if (import3.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setText(this._text_3,currVal_18);
      this._expr_18 = currVal_18;
    }
    this._RouterLinkWithHref_5_3.checkHost(this,this,this._el_5,throwOnChange);
    const currVal_21:any = import3.inlineInterpolate(1,'',this.context.$implicit.Text,'');
    if (import3.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setText(this._text_6,currVal_21);
      this._expr_21 = currVal_21;
    }
  }
  destroyInternal():void {
    this._RouterLinkWithHref_2_3.ngOnDestroy();
    this._RouterLinkActive_2_4.ngOnDestroy();
    this._RouterLinkWithHref_5_3.ngOnDestroy();
    this._RouterLinkActive_5_4.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_2_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_5(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_5_3.handleEvent(eventName,$event) && result);
    return result;
  }
}